const wordList = [
    { word: "apple", hint: "A fruit that keeps the doctor away" },
    { word: "elephant", hint: "A large animal with a trunk" },
    { word: "sun", hint: "The star that lights up our day" },
    { word: "hate", hint: "Intense dislike." },
    { word: "good", hint: "Morally right or virtuous." },
    { word: "bad", hint: "Not good; unpleasant." },
    { word: "easy", hint: "Not difficult." },
    { word: "ocean", hint: "A vast body of salt water" },
    { word: "piano", hint: "A musical instrument with black and white keys" },
    { word: "happy", hint: "Feeling good or content." },
    { word: "slow", hint: "Moving at a low speed." },
    { word: "hot", hint: "Having a high temperature." },
    { word: "cold", hint: "Having a low temperature." },
    { word: "love", hint: "A deep feeling of affection." },
    { word: "hard", hint: "Requiring effort." },
    { word: "new", hint: "Not existing before." },
    { word: "smart", hint: "Intelligent." },
    { word: "square", hint: "Four equal sides." },
    { word: "circle", hint: "Round shape, no sides." },
    { word: "perimeter", hint: "Distance around a shape." },
    { word: "sad", hint: "Feeling unhappy or sorrowful." },
    { word: "big", hint: "Large in size." },
    { word: "small", hint: "Little in size." },
    { word: "fast", hint: "Moving quickly." },
    { word: "fraction", hint: "Part of a whole." },
    { word: "decimal", hint: "Number with a point." },
    { word: "dumb", hint: "Lacking intelligence." },
    { word: "clean", hint: "Free from dirt." },
    { word: "dirty", hint: "Covered with dirt." },
    { word: "light", hint: "Not heavy." },
    { word: "heavy", hint: "Having a lot of weight." },
    { word: "bright", hint: "Giving out a lot of light." },
    { word: "dark", hint: "Lacking light." },
    { word: "sweet", hint: "Having a sugary taste." },
    { word: "sour", hint: "Having an acidic taste." },
    { word: "old", hint: "Having lived for a long time." },
    { word: "young", hint: "Having lived or existed for a short time." },
    { word: "beautiful", hint: "Pleasing to the eye." },
    { word: "ugly", hint: "Unpleasant to look at." },
    { word: "tall", hint: "High in height." },
    { word: "soft", hint: "Pleasantly smooth or gentle." },
    { word: "multiplication", hint: "Repeated addition." },
    { word: "division", hint: "Splitting into equal parts." },
    { word: "short", hint: "Small in height." },
    { word: "rich", hint: "Having a lot of money." },
    { word: "poor", hint: "Lacking sufficient money." },
    { word: "strong", hint: "Having power." },
    { word: "weak", hint: "Lacking strength." },
    { word: "bitter", hint: "Having a sharp taste." },
    { word: "salty", hint: "Tasting like salt." },
    { word: "hungry", hint: "Needing food." },
    { word: "thirsty", hint: "Needing a drink." },
    { word: "awake", hint: "Not asleep." },
    { word: "addition", hint: "Putting numbers together." },
    { word: "subtraction", hint: "Taking numbers away." },
    { word: "funny", hint: "Causing laughter." },
    { word: "serious", hint: "Not joking." },
    { word: "quiet", hint: "Making little noise." },
    { word: "loud", hint: "Making a lot of noise." },
    { word: "radius", hint: "Center to edge of a circle." },
    { word: "diameter", hint: "Edge to edge through center." },
    { word: "equation", hint: "Mathematical statement with an equals sign." },
    { word: "angle", hint: "Measured in degrees." },
    { word: "volume", hint: "Space a 3D object occupies." },
    { word: "area", hint: "Space a 2D object occupies." },
    { word: "sleepy", hint: "Needing sleep." },
    { word: "hard", hint: "Solid, firm, and rigid." },
    { word: "wet", hint: "Covered with liquid." },
    { word: "dry", hint: "Free from moisture." },
    { word: "triangle", hint: "Three sides, three angles." },
    { word: "exponent", hint: "Indicates repeated multiplication." },
    { word: "integer", hint: "Whole number, positive or negative." },
    { word: "variable", hint: "Represents an unknown value." },
    { word: "geometry", hint: "Study of shapes and space." }
]